### ISSUE TITLE
Fix for -projectPath command line argument

### ISSUE THREAD

**Issue by 3DCraphael** [JetBrains/teamcity-unity-plugin#21]
I always get an error for the project path (`Couldn't set project path to: ./`)

I tried this with a minimal setup; a new unity project, with the project root folder also being the git root folder and thus leaving "Working Directory" and "Project path" empty. Searching for a solution, I found this post on Unity answers:
https://answers.unity.com/questions/622429/i-have-a-problem-the-log-is-couldnt-set-project-pa.html

One of the answers mentions "You need to format the option -projectPath=/Users/you/pathtoproject with an equals sign between -projectPath and the path rather than a space as indicated in the documentation."

Why has nobody else complained about this yet? Because it seems as if - instead of fixing the documentation - the fixed this in the software in Unity 2018. It failed for me in 5.x and 2017.1.0f3, but it worked fine in 2018.2.6f1.

**Comment by dtretyakov** [comment]
@3DCraphael, thank you for reporting and providing workaround for that.

**Comment by tplester** [comment]
This still seems to be an issue in Unity 2018.1.3 with plugin version `SNAPSHOT-20190307144314`

**Comment by dtretyakov** [comment]
@tplester, thanks for reporting it'll be fixed in #29

**Comment by tplester** [comment]
On further examination, it seems that using `-projectPath=./` doesn't work in Unity 2018.1.3 and Unity will silently ignore the argument, so it can appear to work because you don't get the `Couldn't set project path to: ./` error anymore, but instead Unity will just use the last project path used. The solution (for at least 2018.1.3) is to use `-projectPath <absolute path>` as it seems to be the relative path that Unity is complaining about

**Comment by dtretyakov** [comment]
@tplester, thanks for investigation, we'll apply this suggestion.
