### ISSUE TITLE
License Activation not working

### ISSUE THREAD

**Issue by AleBles** [JetBrains/teamcity-unity-plugin#46]
Hi there!

I'm running into an issue where the license couldn't activated in the Build Feature and therefor the build fails.

In the buildlog I see a double declaration to /Editor/Unity.exe (windows agent):
```
  Starting: "C:\Unity\Unity 2019.2.12\Editor\Unity.exe\Editor\Unity.exe" -quit -batchmode -nographics -serial ******* -username ****** -password ******* -logFile C:\buildAgent\temp\buildTmp\unityBuildLog-8479047412352649534-114640.txt
14:26:17
  Process exited with code -1. Unity log:
```

On the actualy build command itself we're seeing different (correct) behaviour:
```

  Starting: "C:\Unity\Unity 2019.2.12\Editor\Unity.exe" -batchmode -projectPath ./ -quit -logFile C:\buildAgent\temp\buildTmp\unityBuildLog-998815648385366156.txt
```

Could it be something in the plugin or did I misconfigure something.

We're running the latest snapshot from 2020 (SNAPSHOT-20200127164629)

**Comment by badjester** [comment]
We have the same problem.
Our workaround: Currently we need 3 Unity runners for building our project:
1. Returns licence (run Unity with the command lines -quit -batchmode -returnlicense)
2. Import + Licence (Run Unity with command lines including username, password and serial, import project and then quits. Uses a line status file to ignore errors because on many changes unity would only build on the second time. See this issue for more information: https://github.com/JetBrains/teamcity-unity-plugin/issues/16)
3. Actually building step

**Comment by stobbsm** [comment]
I'm having this issue as well. Unity plugin is appending the full path on top of the real path, making the binary "not exist" for it, but the error is reporting as a bad username and password. Doing manually from CLI, with the same credentials but using the proper path, makes it work.

**Comment by stobbsm** [comment]
@NikolayPianikov when is this update going to be pushed to the marketplace so I can update? Also, when I built it an installed myself using the above commit, still having the same issue on MacOS.

Is this even a thing anymore? Should we stop using/paying for teamcity and move on to something that actually works?
